version: '3'

services:
    web:
        build: ./app
        volumes: 
            - ./app:/app
        ports:
            - "5000:5000"
        links:
            - db
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        ports:
            - "3307:3306"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
            - db:/var/lib/mysql
        cap_add:
            - SYS_NICE

    generate_data:
        build: ./generate_data
        volumes:
            - ./generate_data:/app
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        links:
            - db
        profiles:
            - tools
volumes:
    db:
